// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzW0iyt0Mj16pMbSkoJzL1Yfy5UBT7Pa0',
    appId: '1:194230267892:web:7b6516b64b7387cdd013a1',
    messagingSenderId: '194230267892',
    projectId: 'booksstore-60665',
    authDomain: 'booksstore-60665.firebaseapp.com',
    storageBucket: 'booksstore-60665.appspot.com',
    measurementId: 'G-PLXL3KS22K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1JEWAz-0FY16GV87br2__T05l9jOv3q4',
    appId: '1:194230267892:android:6d1328a8ac7e6ec9d013a1',
    messagingSenderId: '194230267892',
    projectId: 'booksstore-60665',
    storageBucket: 'booksstore-60665.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcUUTPJohFYCbV4FjYEmthYtI8P3EvIsg',
    appId: '1:194230267892:ios:5a6fe9e3b18af5d7d013a1',
    messagingSenderId: '194230267892',
    projectId: 'booksstore-60665',
    storageBucket: 'booksstore-60665.appspot.com',
    iosBundleId: 'com.example.onlinebookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcUUTPJohFYCbV4FjYEmthYtI8P3EvIsg',
    appId: '1:194230267892:ios:f0eff65c35832a76d013a1',
    messagingSenderId: '194230267892',
    projectId: 'booksstore-60665',
    storageBucket: 'booksstore-60665.appspot.com',
    iosBundleId: 'com.example.onlinebookstore.RunnerTests',
  );
}
